### ISSUE TITLE
A wiki summarizing current choices for selections (and corresponding plots?)

### ISSUE THREAD

**Issue by nsevilla** [LSSTDESC/DEHSC_LSS#19]
It could be useful to have any selections clearly spelled out somewhere outside the code itself or google slides, as well as any plots associated with such selection somewhere easy to check.

**Comment by nsevilla** [comment]
I think this might need the owner(s) (@damonge ?) to create and give some sort of permissions. Clicking on wiki on the tabs above does not work for me (but it does on my own repos).

**Comment by damonge** [comment]
I see some progress here. Thanks @nsevilla 
Maybe Humna can post the choices of photo-z binning that she's come up with on the wiki.
