### ISSUE TITLE
Likelihood

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/DEHSC_LSS#20]
Write likelihood stage of the pipeline, either based on https://github.com/LSSTDESC/LSSLike, https://github.com/LSSTDESC/TJPCosmo or something else.

Pinging @wagoner47 and @slosar, since they have both expressed willingness to work on this.

**Comment by damonge** [comment]
@slosar is gonna work on this with @humnaawan during the sprint week

**Comment by adam-broussard** [comment]
![likelihood_auto_cross](https://user-images.githubusercontent.com/33520634/47428121-36d22300-d78a-11e8-9bbe-64da9f4c3ca2.png)

**Comment by adam-broussard** [comment]
![likelihood_auto_cross_nocont](https://user-images.githubusercontent.com/33520634/47431150-21152b80-d793-11e8-9f39-661fd95aeac3.png)
Auto-correlation and cross-correlation for the case where contaminants are not marginalized
