### ISSUE TITLE
2pt correlation function implementation

### ISSUE THREAD

**Issue by nsevilla** [LSSTDESC/DEHSC_LSS#22]
This will require an interface to  the DB to download the official random catalogs, and/or produce our own randoms, and compute the two point correlation functions and covariance matrices, possibly based on earlier code from @fjaviersanchez

**Comment by nsevilla** [comment]
A few thoughts on the implementation:
* randoms from the DB do not include any kind of photo-z, so we would have to assign the objects to different bins by hand
* weight calculations to be implemented...
* use fitsio to read instead? (for the larger random files)

**Comment by damonge** [comment]
I don't think we're doing this anymore...
