### ISSUE TITLE
Star Galaxy separation tests

### ISSUE THREAD

**Issue by nsevilla** [LSSTDESC/DEHSC_LSS#32]
Let's collect all plots here

**Comment by nsevilla** [comment]
![classification_acs_vs_wide_median](https://user-images.githubusercontent.com/8889729/47427972-c5927000-d789-11e8-8554-53274d0ac11a.png)

**Comment by damonge** [comment]
Just posting here the numbers @nsevilla has obtained regarding the star densities in other fields:

![stellar_density_ratio](https://user-images.githubusercontent.com/8809493/49918278-63f1a680-fe9a-11e8-986f-989617f7d4eb.png)

VVDS 1.38
GAMA09 1.34
GAMA15 1.47
WIDE12 0.81
XMMLSS 0.65
These are the factors by which we should multiply fstar obtained in COSMOS

The next step should be to incorporate these in the pipeline and possibly marginalize over fstar with some prior.

**Comment by damonge** [comment]
We took this into account in the paper. @nsevilla for the win!
