### ISSUE TITLE
Sanity checks for bias

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DEHSC_LSS#36]
If we are still worried about the systematics and the bias results that we are getting, we can try to further limit the sample down to i<22.5 and cross-check with DES data. I also have the galaxy density maps and the systematic maps from DES-SV laying around (with the clean sample up to i~22.5) so, I could try to compute the Cls there and compare to what we get in a similar sample in HSC. I think there's also DES-Y1 data if we want to check several realizations of a field with similar area to those that we are analyzing. @nsevilla should have more information about the availability of the data products (I believe everything is public by now but I am not 100% sure).

@damonge what do you think?

**Comment by damonge** [comment]
I think this could be a really great check if we have the bandwidth to tackle it. Is this something you'd be willing to do, and how much effort do you think it would require you?

One problem might be that the photo-zs are going to be different, but if we phrase it in terms of the effective bias parameters, it could be interesting.

**Comment by fjaviersanchez** [comment]
I'd be willing to do this. I don't think this should take a long time to do (I think we have all the machinery in place and if we decide to go the DES-SV way, I also have the maps on hand). However, if we aim to finish these studies within the next month - month and a half, I can't guarantee to have this finished by then and I wouldn't want to delay this work.

**Comment by damonge** [comment]
Fixed thanks to Jeff!
