### ISSUE TITLE
Comparison with DC2

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/DEHSC_LSS#41]
Look at cosmoDC2 and see how it compares with the best-fit models we obtain from HSC

**Comment by fjaviersanchez** [comment]
This is the HOD for centrals and satellites with i (observed) < 24.5 and z < 1.5 in `cosmoDC2_v.1.1.4_image`:

![image](https://user-images.githubusercontent.com/13971732/56238325-12714800-6043-11e9-9659-e045fd6c840d.png)

**Comment by damonge** [comment]
We figure this one out thanks to Jeff
