### ISSUE TITLE
write a paper

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/DEHSC_LSS#43]
Put all of our results into a manuscript

**Comment by humnaawan** [comment]
@damonge @adam-broussard can you please add the necessary style files needed to compile `main.tex`? i have spent some time getting some of the style files/commenting things out but am getting random version errors with `lipsum.sty` etc.

**Comment by adam-broussard** [comment]
Hi @humnaawan, everything compiles normally for me as is, so I think it might be some sort of local versioning issue.  I have `texlive-latex-base`, `texlive-latex-extra`, and `texlive-latex-recommended` all installed, but if you have only the base package installed, maybe you're missing some packages in the document?
