### ISSUE TITLE
Fix author list

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/DEHSC_LSS#47]
We have some errors with the submitted author list
- Erika's name should read Erika L. Wagoner
- Aphabetical tier is out of order
- Nacho's name should be I. Sevilla-Noarbe

**Comment by egawiser** [comment]
And the alphabetization needs an update (although I don't actually care where my name appears in the list)

**Comment by damonge** [comment]
Ah, good point @egawiser ! Apologies, don't know how that happened...

**Comment by damonge** [comment]
One more: @nsevilla 's name should read "I.Sevilla-Noarbe"
